### PR TITLE
Added fixes for JSON-LD

### LINKED ISSUE #45: addContext when context is an empty json, creates weird json
If you have a json as follows
```json
{
   "@context": {}
}
```
And you call `json.addContext(someUri)`
it will create 
```json
{
   "@context": [{}, "someUri"]
}
```

It should create 
```json
{
   "@context": "someUri"
}
```

### PR DESCRIPTION
**Pull request by umbreak**
Fixes #45, #46,  #47

### CODE REVIEW

File: modules/circe/src/main/scala/ch/epfl/bluebrain/nexus/rdf/circe/JenaModel.scala [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+  }
+
+  /**
+    *
+    * @param json the json to be converted into a [[Model]]
+    * @param base the JSON-LD base
+    * @return a Jena Model if there were no errors an a [[JenaModelErr]] when we encounter errors
+    *         during model creation.
+    */
+  def apply(json: Json, base: String): Either[JenaModelErr, Model] = {
```
Comment (bogdanromanx) [inline modules/circe/src/main/scala/ch/epfl/bluebrain/nexus/rdf/circe/JenaModel.scala]: collapse the apply functions into a single one with `final def apply(json: Json, base: Option[AbsoluteIri])`
